### ISSUE TITLE
Looking for co-maintainers to take over chell ...

### ISSUE THREAD

**Issue by peti** [jmillikin/chell#1]
Patience has released a new version, but unfortunately the API has changed relative to 0.1.x. Would it be possible to get a new release of `chell`, too, that works with the newer version?

**Comment by jmillikin** [comment]
I've not been maintaining this library for a long time. If it's useful to you, I can transfer the Hackage projects to you.

**Comment by peti** [comment]
Thank you very much for the offer. I am not using `chell` myself, though. I just ran into this issue while building some other package that depends on it. So while I do have an interest in `chell`, it's probably not strong enough for me to start hacking the source code. But maybe someone else will see this offer and take you up on it ...

**Comment by chris-martin** [comment]
@jmillikin I would be happy to take over ownership; love to help get the whole Haskell ecosystem compiling. I'm [chris_martin](https://hackage.haskell.org/user/chris_martin) on Hackage.

**Comment by jmillikin** [comment]
@chris-martin Thanks! I've transferred the three Hackage packages to your account.

Can you fork this repo into your GitHub account? After it's got a new home, I'll close this issue and archive my repository.

**Comment by jmillikin** [comment]
Looks like https://github.com/typeclasses/chell is up and moving. Archiving now.
